In [3]:
import numpy as np

### Task 1

In [4]:
a = np.array([[1, 6], 
              [2, 8], 
              [3, 11], 
              [3, 10], 
              [1, 7]])

In [5]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

### Task 2

In [6]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Task 3

In [35]:
d = a_centered.transpose()
d

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

In [36]:
a_centered_sp = np.dot(d[0], d[1])
a_centered_sp

8.0

In [37]:
a_centered_sp/(len(d[0])-1)

2.0

### Task 4

In [43]:
a_cov = np.cov(a.transpose())
a_cov

array([[1. , 2. ],
       [2. , 4.3]])

In [44]:
a_cov[0][1]

2.0